### ISSUE TITLE
Modify visualization.py to write playlist URL to file

### ISSUE THREAD

**Issue by dtcrout** [dtcrout/spotitude#10]
There is currently an enhancement for generating a playlist based on the top 25 tracks returned to the user. In that class will exist a url to the playlist. I'll leave this up to the person working on this task, but the URL should be rendered in the visualization.

**Comment by HAKSOAT** [comment]
Hello, all this task needs is to have the URL added to the visualization, right?

**Comment by nicofilliol** [comment]
Instead of just directly creating the playlist without user approval and displaying the URL in the visualisation, something like [Eel](https://github.com/ChrisKnott/Eel) could be used to open the `index.html` and to establish a "conncection" between the frontend and python. I just played around with it a bit and I was able to add a `Create playlist` button to the HTML which would trigger a function in the python script which in turn then makes use of the playlist class to create the spotitude playlist and open the URL in a new window. @dtcrout What do you think of this idea?

**Comment by dtcrout** [comment]
@nicofilliol, you bring up a good point. The playlist URL will only be generated if a user chooses to create a playlist, therefore a mechanism should exist to run the command.

If you want to create this functionality using Eel, that would be fantastic!

**Comment by aditj** [comment]
Is this issue assigned or can I work on it?

**Comment by nicofilliol** [comment]
@aditj I would actually like to give this a go since I already have a working solution and just need to polish it a bit.

**Comment by aditj** [comment]
> @aditj I would actually like to give this a go since I already have a working solution and just need to polish it a bit.

No Problem @nicofilliol  :)
