### ISSUE TITLE
Install dependencies in a virtual environment

### ISSUE THREAD

**Issue by zackelia** [dtcrout/spotitude#17]
It would be better to have the makefile configure dependencies in a virtual environment rather than in the global environment where there could eventually be potential conflicts with other projects.

**Comment by dtcrout** [comment]
Great suggestion @zackelia !

For this improvement, one would need to modify the `Makefile`to
* create a virtual environment
* install the dependencies in that virtual env

Spotitude will then need to be ran within that virtual environment. Since it's not launched through the `Makefile`, the `README.md` would need to be updated accordingly.

**Comment by thinkgruen** [comment]
Added PR #19. Please let me know what you think.
